name: interview_question
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.7.0
  dart_numerics: ^0.0.5
  useful_extension: ^1.0.2+4

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.0.0